include $(THEOS)/makefiles/common.mk

TWEAK_NAME = WipeCodePref

WipeCodePref_FILES = WipeCodePref.m
WipeCodePref_CFLAGS = -fobjc-arc -I../common
WipeCodePref_FRAMEWORKS = Foundation CoreFoundation UIKit WebKit

include $(THEOS_MAKE_PATH)/tweak.mk
