include $(THEOS)/makefiles/common.mk

TWEAK_NAME = WipeCodeSB

WipeCodeSB_LOGOS_FILES = WipeCodeSB.m
WipeCodeSB_CFLAGS = -fobjc-arc -I../common
WipeCodeSB_FRAMEWORKS = Foundation CoreFoundation UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
