include $(THEOS)/makefiles/common.mk

TWEAK_NAME = WipeCode

WipeCode_LOGOS_FILES = WipeCode.x
WipeCode_CFLAGS = -fobjc-arc -I../common
WipeCode_FRAMEWORKS = Foundation CoreFoundation UIKit WebKit Preferences

include $(THEOS_MAKE_PATH)/tweak.mk
